imports:
    - { resource: parameters.ini }

framework:
    templating:
        engines: ['twig']
    # Required for the uri_signer service, which is always enabled.
    secret: secret

platinum_pixs_aws:
    base:
        key: %aws_access_key_id%
        secret: %aws_secret_key%
        region: %aws_region%

roh_temporal_scaling:
    calendar_sources: {}
